### PR TITLE
Added Gitpod config

### PR DESCRIPTION
**Pull request by svenefftinge**
Hey 👋 

I notice you were asking for a [Gitpod config](gdejohn/procrastination#21) :)
So please have a look. I still have issues for which I'd need a little help from you as my Java skills are a bit rusty:
 - the tests don't run through (I tried `mvn verify` probably I'm missing something)
 - the type-inference of the language server cannot deal with some of your code. (I checked in Eclipse and see the same)

You can check the current state here:
https://gitpod.io/#https://github.com/svenefftinge/procrastination/tree/GH-21

Fixes gdejohn/procrastination#21

### CODE REVIEW

**Comment by gdejohn** [comment]
Hi! Thanks for the contribution!

When I run `mvn --version` in the Gitpod workspace, I get this:

```
gitpod /workspace/procrastination $ mvn --version
Picked up JAVA_TOOL_OPTIONS: -Xmx3543m
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /home/gitpod/.sdkman/candidates/maven/current
Java version: 1.8.0_202, vendor: Azul Systems, Inc., runtime: /home/gitpod/.sdkman/candidates/java/8.0.202-zulufx/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1028-gcp", arch: "amd64", family: "unix"
```

So it looks like it's trying to use Java 8 when you run `mvn verify`, which would explain why that fails.

I'm not sure what to do about the issue with the type inference. I'm using IntelliJ, which handles it fine. But I do see issues when I try to open the project in VS Code. Is it possible that Gitpod won't be usable for this project until the Java Language Server is more advanced?

**Comment by svenefftinge** [comment]
Oh, interesting that mvn runs the wrong version. We'll investigate.

> Is it possible that Gitpod won't be usable for this project until the Java Language Server is more advanced?

If this really is a shortcoming of the Java LS. I saw the same issue when testing in Eclipse.

**Comment by gdejohn** [comment]
> If this really is a shortcoming of the Java LS. I saw the same issue when testing in Eclipse.

The Red Hat Java language support VS Code extension uses the same language server that Eclipse uses, right? And that's the VS Code extension that Gitpod uses for Java?

**Comment by svenefftinge** [comment]
Yes, Eclipse, VS Code and Gitpod are all running JDT-LS. I have asked on the JDT forum:
https://www.eclipse.org/forums/index.php/m/1808350/#msg_1808350

**Comment by gdejohn** [comment]
> Oh, interesting that mvn runs the wrong version. We'll investigate.

Any update on this part?

**Comment by svenefftinge** [comment]
Sorry, for the delay. I just tried again and the output looks good:
```
gitpod /workspace/procrastination $ mvn --version
Picked up JAVA_TOOL_OPTIONS: -Xmx3543m
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T19:00:29Z)
Maven home: /home/gitpod/.sdkman/candidates/maven/current
Java version: 11.0.2, vendor: Azul Systems, Inc., runtime: /home/gitpod/.sdkman/candidates/java/11.0.2-zulufx
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1028-gcp", arch: "amd64", family: "unix"
```

**Comment by svenefftinge** [comment]
But the type checking issues remain :-(

**Comment by gdejohn** [comment]
> But the type checking issues remain :-(

I'm not very happy that Stephan expects us to become experts on JLS type inference before he'll investigate a possible defect on his end. That sounds a bit too daunting for me at the moment, so I'm gonna close this pull request for now. But I appreciate your efforts, and I do still want people to be able to use Gitpod with this project eventually. So I will periodically revisit this to see if the JDT language server has improved in this regard. If and when that happens, I'll reopen this.

**Pull request closed without merging**
